### ISSUE TITLE
Enhance your footer

### ISSUE THREAD

**Issue by henry-dura** [DilsherB/Portfolio#6]
check your Figma you are missing a border radius on the corner top left
![Dilsher](https://user-images.githubusercontent.com/80098545/206385378-e97f104e-bee1-42ae-a9ca-af567d7c2cba.png)

**Comment by DilsherB** [comment]
I really appreciate your close look at my project. Thanks for pointing out the issue.

**Comment by raezon** [comment]
I agree we've witnessed that you must fix that

**Comment by alicemirigo92** [comment]
The border was added and gave it a nice look.

**Comment by henry-dura** [comment]
I agree it needs to be changed to follow the Figma design strictly.
